apiVersion: v1
kind: Pod
metadata:
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/bettercallpavan"
    vault.hashicorp.com/agent-inject-template-server.key: |
      {{- with secret "pki/issue/bettercallpavan" "common_name=test.betetrcallpavan.com" -}}
      {{ .Data.private_key }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-server.crt: "pki/issue/bettercallpavan"
    vault.hashicorp.com/agent-inject-template-server.crt: |
      {{- with secret "pki/issue/bettercallpavan" "common_name=test.betetrcallpavan.com" -}}
      {{ .Data.certificate }}
      {{- end }}
    vault.hashicorp.com/role: "issuer"
  labels:
    run: pki-test
  name: pki-test
spec:
  serviceAccountName: issuer
  containers:
  - image: nginx
    name: pki-test
  restartPolicy: Always
