apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-hot
  namespace: es
spec:
  version: 7.12.1
  http:
    service:
      metadata:
        annotations:
          elasticsearch.k8s.elastic.co/node-master: "false"
      spec:
        type: LoadBalancer
  nodeSets:
  - name: hot-node
    count: 1
    config:
      node.roles: [ data_hot, data_content ]
      node.store.allow_mmap: false
      xpack:
        security:
          authc:
            anonymous:
              authz_exception: false
              roles: superuser
              username: anonymous
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: hostpath
  - name: master-zone-c
    count: 1
    config:
      node.ml: false
      node.store.allow_mmap: false
      node.master: true
      node.data: false
      xpack:
        security:
          authc:
            anonymous:
              authz_exception: false
              roles: superuser
              username: anonymous
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: hostpath
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 1Gi
