apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rasa-enterprise
  namespace: rasa
spec:
  interval: 30m
  url: https://rasahq.github.io/rasa-x-helm

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rasa-enterprise
  namespace: rasa
spec:
  interval: 5m
  targetNamespace: "rasa"
  install:
    createNamespace: true
  releaseName: rasa-enterprise
  chart:
    spec:
      chart: rasa-x
      version: 4.5.5
      sourceRef:
        kind: HelmRepository
        name: rasa
