apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: neo4j
  namespace: kube-tools
spec:
  interval: 30m
  url: https://helm.neo4j.com/neo4j

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j-lb
  namespace: kube-tools
spec:
  interval: 5m
  targetNamespace: "kube-tools"
  install:
    createNamespace: true
  releaseName: neo4jlb
  chart:
    spec:
      chart: neo4j-cluster-loadbalancer
      version: 4.4.9
      sourceRef:
        kind: HelmRepository
        name: neo4j

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j-cluster
  namespace: kube-tools
spec:
  interval: 5m
  targetNamespace: "kube-tools"
  install:
    createNamespace: true
  releaseName: neo4jcluster
  chart:
    spec:
      chart: neo4j-cluster-core
      version: 4.4.9
      sourceRef:
        kind: HelmRepository
        name: neo4j
