apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: neo4j
  namespace: kube-tools
spec:
  interval: 30m
  url: https://helm.neo4j.com/neo4j

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j-lb
  namespace: kube-tools
spec:
  interval: 5m
  targetNamespace: "kube-tools"
  install:
    createNamespace: true
  releaseName: neo4j-lb
  chart:
    spec:
      chart: neo4j-cluster-loadbalancer
      version: 4.4.9
      sourceRef:
        kind: HelmRepository
        name: neo4j

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j-cluster
  namespace: kube-tools
spec:
  interval: 5m
  targetNamespace: "kube-tools"
  install:
    createNamespace: true
  releaseName: neo4j-cluster
  chart:
    spec:
      chart: neo4j-standalone
      version: 4.4.9
      sourceRef:
        kind: HelmRepository
        name: neo4j
  values:
    volumes:
      data:
        mode: "defaultStorageClass"
    config:
      statefulset:
        podSpec:
          volumes:
          - name: plugin-volume
            emtyDir: {}
        containers:
        - volumeMounts:
          - mountPath: /var/lib/neo4j/plugins
            name: plugin-volume
        initContainers:
        - command:
          - /bin/sh
          - -c
          - |
            "curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.3.0.4/apoc-3.3.0.4-all.jar -O 
            curl -L https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.3.5.0/graph-algorithms-algo-3.3.5.0.jar -O
            curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.11.250/aws-java-sdk-core-1.11.250.jar -O
            curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.11.250/aws-java-sdk-s3-1.11.250.jar -O
            curl -L https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.4/httpclient-4.5.4.jar -O
            curl -L https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.8/httpcore-4.4.8.jar -O
            curl -L https://repo1.maven.org/maven2/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar -O
            chmod 755 *.jar
            mv *.jar /var/lib/neo4j/plugins"
        volumeMounts:
        - mountPath: /var/lib/neo4j/plugins
          name: plugin-volume
