---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
