apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-helm
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-server
  namespace: minio
spec:
  interval: 10m
  chart:
    spec:
      chart: minio
      version: '14.6.7'
      sourceRef:
        kind: HelmRepository
        name: minio-helm
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: bitnami/minio
      tag: 2024.6.11
    mode: standalone
    replicaCount: 1
    persistence:
      enabled: true 
      size: 100Gi
    provisioning:
      enabled: true
      buckets:
        - name: medium-stats
        - name: iceberg-table
