apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-system
spec:
  interval: 10m
  install: 
    createNamespace: true
  chart:
    spec:
      chart: rook-ceph
      version: '0.0.1'
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
      interval: 1m
