apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-system
spec:
  interval: 10m
  install: 
    createNamespace: true
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 'v1.14.5'
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
      interval: 1m
  values:
    operatorNamespace: rook-system
    cephClusterSpec:
      mon:
        count: 1
      mgr:
        count: 1
      dashboard:
        enabled: true
        ssl: false

