apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama-helm
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.openwebui.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama-server
  namespace: ollama
spec:
  interval: 10m
  chart:
    spec:
      chart: open-webui
      version: '2.1.0'
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
        namespace: flux-system
      interval: 1m
  values:
    ollamaUrls:
    - 'http://ollama-server:11434'
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "4Gi"
    ollama:
      # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
      enabled: true
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "4000m"
          memory: "4Gi"
      replicaCount: 2
      ollama:
        models:
        - gemma
        - mistral
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 3
        targetCPUUtilizationPercentage: 50
      persistentVolume:
        enabled: true
        accessModes:
        - ReadWriteOnce
        size: 100Gi
        storageClass: "ceph-block"
