name: Delete Deploy Keys

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  delete_deploy_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pip3
        run: |
          pip install requests==2.31.0

      - name: Run script
        run: |
          python scripts/delete_deploy_keys.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
